### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by StSimmons** [Timdawson264/acdfuse_c#1]
Maybe a stupid question, but this src fails to build (libsqlite3-dev etc installed)

/usr/bin/ld: /tmp/ccvXS1hF.o: undefined reference to symbol 'sqlite3_close'
//usr/lib/x86_64-linux-gnu/libsqlite3.so.0: error adding symbols: DSO missing from command line

**Comment by StSimmons** [comment]
Adding -lsqlite3 fixed it

**Comment by Timdawson264** [comment]
Ill add a proper build system soon.
