### ISSUE TITLE
Can't write files/directories.

### ISSUE THREAD

**Issue by fling-** [Timdawson264/acdfuse_c#3]
Looks like I can't write to the mounted dir.

```
fling@studio ~/mnt/acd $ mount | grep acd
acdfuse on /home/fling/mnt/acd type fuse.acdfuse (rw,nosuid,nodev,user=fling)
fling@studio ~/mnt/acd $ touch test
touch: cannot touch 'test': Function not implemented
```

How to fix?

**Comment by msh100** [comment]
I believe `acdfuce_c` does not support write functions.

**Comment by Timdawson264** [comment]
and you would be correct, maby in the future but this fs will probobly be RO for a long time.

**Comment by Slennox** [comment]
Hi, Tim. 

Is there nothing we can do to speed up copying/transferring files to an ACD mountpoint? When using acd_cli upload you can get 10x the speed than using a FUSE mounted filesystem through acd_cli mount...

acd_cli process goes to 100% CPU usage while using a simply cp of a large file. Just test.

**Comment by Timdawson264** [comment]
I havnt got time to make thise fuse filesystem writable before I do that I
need todo oauth stuff. However with acdcli try setting the max  write size
fuse option
